apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  ports:
    - port: 31000
      nodePort: 31000
      targetPort: nodejs-port
      protocol: TCP
  selector:
    app: helloworld
  type: NodePort
