apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        ver: blue
    spec:
      containers:
        - name: k8s-demo
          image: mikeqiu2011/node-hostname:v1
          ports:
            - name: nodejs-port
              containerPort: 3000
